### ISSUE TITLE
Specify dependencies in setup.py/requirements.txt

### ISSUE THREAD

**Issue by mitakas** [jm-begon/globally-induced-forest#1]
I tried to install the package in a new virtualenv, but got the error that numpy is not installed. I saw in `setup.py` that the installation routine is largely based on the one in scikit-learn, but in newer versions of scikit-learn numpy is automatically installed if not found, for example the approach taken in [issue 4164 in scikit-learn](https://github.com/scikit-learn/scikit-learn/issues/4164).

A quick fix would be to include a `requirements.txt`, so that users can install the dependencies using `pip install -r requirements.txt`. Here are the contents of the `requirements.txt` that worked for me:

```
six==1.10.0
numpy==1.11.3
scipy==0.18.1
scikit-learn==0.18.1
```

**Comment by jm-begon** [comment]
Thanks for the end ups. I added a `requirements.txt` file along with some more instructions in the readme. (19c9822529d8fa271001c2ead0c05e6a50fbe107, e27911d54c3eac6c8434b72edc80299d111576e7, 3c3a5bf00b5d01aee472eb3c3eb59576d2860d0e)
